Add some options to make-bm-worke
metal3-io/baremetal-operator pull request #1039
Opened 2021-11-24 03:02 UTC by zhouhao3

Improve the options of make-bm-worke so that it can generate more detailed yaml

2021-12-01 10:38 UTC, hardys commented
/ok-to-test
/retitle Add some options to make-bm-worker

2021-12-01 10:41 UTC, hardys commented
> Regular contributors should join the org to skip this step.

Hi @zhouhao3 - thanks for your PR, I can see you've been regularly contributing so I sent an invite to join the org, this means your PRs will not require the manual ok-to-test step in future :)

2021-12-02 01:53 UTC, zhouhao3 commented
/test-v1b1-centos-integration
/test-v1b1-integration

2021-12-02 01:56 UTC, zhouhao3 commented
@fmuyassarov @andfasano @s3rj1k @dtantsur PTAL

2021-12-10 13:21 UTC, andfasano commented
/lgtm

2021-12-10 13:44 UTC, fmuyassarov commented on cmd/make-bm-worker/main.go
> +		fmt.Fprintf(os.Stderr, "Invalid automatic cleaning mode %q, use \"metadata\" or \"disabled\"\n", *bootMode)
```suggestion
		fmt.Fprintf(os.Stderr, "Invalid automatic cleaning mode %q, use \"metadata\" or \"disabled\"\n", *automatedCleaningMode)
```

2021-12-10 14:20 UTC, furkatgofurov7 requested changes

2021-12-10 14:20 UTC, furkatgofurov7 commented on cmd/make-bm-worker/main.go
> +		"image-checksum-type", "", "checksum algorithm for the image (md5, sha256 or sha256)")
duplicate `sha256`, should be `sha512`

2021-12-13 03:57 UTC, zhouhao3 commented
/test-v1b1-integration
/test-v1b1-centos-integration

2021-12-15 16:59 UTC, andfasano commented
/lgtm

2021-12-17 06:55 UTC, zhouhao3 commented
/test-v1b1-integration
/test-v1b1-centos-integration

2021-12-17 07:16 UTC, fmuyassarov commented
@zhouhao3 this looks good to me. Can we squash the commits before merging ?

2021-12-17 08:02 UTC, zhouhao3 commented
> Can we squash the commits before merging ?

Done, PTAL.

2021-12-17 08:05 UTC, zhouhao3 commented
/test-v1b1-integration
/test-v1b1-centos-integration

2021-12-17 11:42 UTC, fmuyassarov reviewed
Thank you!
/lgtm

2021-12-17 14:53 UTC, andfasano commented
/approve

2021-12-17 14:57 UTC, merged