🌱 Add dependabot workflow and configuration
metal3-io/baremetal-operator pull request #1287
Opened 2023-06-19 19:16 UTC by kashifest

This PR adds dependabot configuration which enables dependabot to automatically open PRs for bumping go modules and tags while ignoring a few of the gomodule update for example controller-runtim or k8s.io/* for manual bumping. This will run as a github workflow.

2023-06-19 20:49 UTC, tuminoid requested changes

2023-06-19 20:49 UTC, tuminoid commented on Makefile
This is not relevant for this PR. Mistakenly added to the commit?

2023-06-20 05:52 UTC, kashifest commented on Makefile
Actually it is, we missed this in CAPM3 and IPAM, I am adding it for CAPM3 https://github.com/metal3-io/cluster-api-provider-metal3/pull/1028 and for IPAM we need to add it as well. It is used by dependabot [here](https://github.com/metal3-io/baremetal-operator/pull/1287/files#diff-844c68181213ce31638b949e99f9f4df97859cb53840020a31c603a236346ba6R24)

2023-06-20 06:06 UTC, tuminoid commented on Makefile
How do they work without it :) Anyways, resolved.

2023-06-20 06:06 UTC, tuminoid reviewed
/lgtm

2023-06-20 06:06 UTC, tuminoid approved these changes

2023-06-20 06:07 UTC, tuminoid commented
/test-ubuntu-integration-main  
/test-centos-e2e-integration-main

2023-06-20 11:57 UTC, honza commented
/approve

2023-06-20 11:58 UTC, merged