WIP: 🌱 Use equinix runner instead of ubuntu for e2e tests
metal3-io/baremetal-operator pull request #1775
Opened 2024-06-07 06:27 UTC by kashifest

2024-06-10 07:36 UTC, tuminoid commented
/retest

2024-06-10 07:43 UTC, tuminoid commented
Please add proper description and link to the relevant GH doc.

It seems, e2e pipeline did not get a runner, as they are just "failed" with no run logs. Do we really want to use Equinix as they seem to be off most of the time?

2024-06-10 11:13 UTC, kashifest commented
> Please add proper description and link to the relevant GH doc.
> 

Its a WIP so not ready for review, I will add description once we know it works.

2024-06-10 11:15 UTC, kashifest commented
> It seems, e2e pipeline did not get a runner, as they are just "failed" with no run logs. Do we really want to use Equinix as they seem to be off most of the time?

We were suggested to try them in the CNCF cluster issue here https://github.com/cncf/cluster/issues/266#issuecomment-2153144241 . I have replied back what we experienced here.

2024-07-12 10:02 UTC, Rozzii commented
/retest

2024-07-12 10:25 UTC, Rozzii commented
/ok-to-test

2024-09-13 13:17 UTC, kashifest commented
/retest

2024-10-22 10:52 UTC, kashifest commented
/retest

2024-10-22 13:13 UTC, tuminoid commented
> /retest

Still queued after 2.5 hours.

2024-10-22 14:04 UTC, RobertKielty commented
@tuminoid @kashifest I am troubleshooting this right now, thank you for your patience. 

The two pending jobs are 

https://github.com/metal3-io/baremetal-operator/actions/runs/11459855378/job/31885474716?pr=1775

and 

https://github.com/metal3-io/baremetal-operator/actions/runs/11459855378/job/31885475330?pr=1775

2024-10-22 15:02 UTC, RobertKielty commented
We are still working on determining the root cause of the problem. 

Since the last update, we have reviewed and checked org-level settings and restarted a cluster listener that should be picking this job up. I canceled and restarted the failed jobs a few times. We will continue to work on this and update you again in an hour.

Thanks again for your patience. Let me know if this is an immediate blocker for the project. If not we appreciate your adoption of the runner and giving us this opportunity to figure out how to fix this.

2024-10-22 15:30 UTC, RobertKielty requested changes
We think that changing this line back to

`runs-on: ${{ inputs.runner }}`

will enable the job to be picked up by the appropriate CNCF Managed External GitHub Action runner.

2024-10-23 05:56 UTC, tuminoid commented
It seems to have picked it up, but fails very early.

```console
Run sudo usermod -a -G libvirt $USER
Usage: usermod [options] LOGIN
...
```

2024-10-23 07:29 UTC, kashifest commented
> It seems to have picked it up, but fails very early.
> 
> ```
> Run sudo usermod -a -G libvirt $USER
> Usage: usermod [options] LOGIN
> ...
> ```

Yeah, @RobertKielty what kind of OS and which versions are these runners using? It would be good if you can point us to detailed information on these runners.

2024-10-23 08:39 UTC, RobertKielty commented
@kashifest, you are correct that documentation is needed to describe the runners; full end-user documentation is not yet ready, as this iteration of the runners was deployed last week.

The cluster and external runners are defined in the ci directory on the cncf/automation repo. 

So we can review the code that created the runners.

The `equinix-4cpu-16gb` runner is deployed from the following directory which contains a Helm Chart and associated values file. (Runner Helm Charts and related components are deployed using ArgoCD but that should not be relevant)

https://github.com/cncf/automation/tree/main/ci/cluster/equinix/runners/4cpu-16gb

The Container Image is defined here
https://github.com/cncf/automation/tree/main/ci/gha-runner-image

Looking at the Dockerfile we have 

# This exists till https://github.com/actions/runner/pull/3056 is merged
FROM ghcr.io/actions/actions-runner:latest

```
USER root
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
    build-essential \
    npm \
    git \
    curl \
    jq \
    unzip \
    kmod

USER runner
```
The GHA runner image we use is based on ghcr.io/actions/actions-runner:latest from 

https://github.com/actions/runner

We add typically needed packages as root and then revert to the `runner` user

Apologies again for not having full documentation in place; it is on our roadmap. Any and all feedback is very much appreciated!

2024-11-26 07:38 UTC, tuminoid commented
/retest

2024-11-26 07:45 UTC, tuminoid commented
/retest

2024-11-26 07:46 UTC, tuminoid commented
/retest

2024-11-26 08:02 UTC, tuminoid commented
OK, we're still missing Prow image bumps, no wonder it did not work. I'll retry later.

2024-11-26 10:29 UTC, tuminoid commented
/retest

2024-11-26 10:31 UTC, tuminoid commented
/retest

2024-11-26 11:01 UTC, tuminoid commented
One last try.

/retest

2024-11-26 11:02 UTC, tuminoid commented
/test all

2025-03-18 11:38 UTC, tuminoid commented
Given Equinix metal is sunsetting, I think we should close this PR.
https://deploy.equinix.com/blog/sunsetting-equinix-metal/

/close

2025-03-18 11:38 UTC, closed without merging